# Generated by Django 6.0.7 on 2026-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
    ]
